_format_version: "2.1"
_transform: true

services:
  - name: echo
    host: ${ECHO_URL}
    routes:
      - paths:
          - "/echo"

  - name: auth
    host: ${AUTH_URL}
    port: ${AUTH_PORT}
    routes:
      - name: auth
        strip_path: true
        paths: [ "/auth" ]
        methods: [ "POST", "GET" ]
      - name: health
        strip_path: false
        paths: [ "/health" ]
        methods: [ "GET" ]

    plugins:
      - name: my-plugin
        config:
          headerkey: "test-header"
