version: '3'

services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"  
      - "8600:8600/udp" 
    networks:
      - mygrpcnetwork
  sm-db:
    container_name: sm-db
    image: kaium123/sm-db
    ports:
      - "54321:5432"

    volumes:
      - sm-db:/var/lib/postgresql
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: 12345678
    networks:
      - mygrpcnetwork
    restart: unless-stopped

  app-service:
    image: kaium123/app:2
    container_name: app-service
    ports:
      - "50051:50051"
    networks:
      - mygrpcnetwork
    depends_on:
      - sm-db
    restart: unless-stopped
    environment:
      CONSUL_PATH: app
      CONSUL_URL: consul:8500

  envoy-proxy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    container_name: envoy_container
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8081:8081"
      - "8085:8085"
    # depends_on:
    
    #   - app-service
    networks:
      - mygrpcnetwork

  kong:
    build:
      context: .
      dockerfile: Dockerfile.kong
    container_name: kong_container
    environment:
        - KONG_DATABASE=off
        - KONG_GO_PLUGINS_DIR=/app/go-plugins
        - KONG_DECLARATIVE_CONFIG=/home/kong/config.yml
        - KONG_PLUGINS=bundled,my-plugin
        - KONG_PLUGINSERVER_NAMES=my-plugin
        - KONG_PLUGINSERVER_MY_PLUGIN_START_CMD=/app/go-plugins/my-plugin
        - KONG_PLUGINSERVER_MY_PLUGIN_QUERY_CMD=/app/go-plugins/my-plugin -dump
        - KONG_PROXY_LISTEN=0.0.0.0:8000
        - KONG_ADMIN_LISTEN=0.0.0.0:8001
        - KONG_LOG_LEVEL=debug
        - KONG_PROXY_ACCESS_LOG=/dev/stdout
        - KONG_ADMIN_ACCESS_LOG=/dev/stdout
        - KONG_PROXY_ERROR_LOG=/dev/stderr
        - KONG_ADMIN_ERROR_LOG=/dev/stderr
        - KONG_NGINX_MAIN_ENV=RLS_DEBUG;env AUTH_URL; env AUTH_PORT; env EXPIRATION_TIME
        - RLS_DEBUG=true
        - AUTH_URL=envoy_container
        - AUTH_PORT=8085
        - ECHO_URL=echo
        - ENVOY_URL=envoy_container
        - ENVOY_PORT=8085
        - EXPIRATION_TIME=10
    volumes:
        - ./plugin/config.yml:/home/kong/config.yml:Z
    ports:
        - '8000:8000'
        - '8001:8001'
        - '8443:8443'
        - '8444:8444'
    networks:
      - mygrpcnetwork
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  echo:
    image: ealen/echo-server
    container_name: echo
    networks:
      - mygrpcnetwork

  auth:
    container_name: auth
    image: kaium123/auth:2
    ports:
      - "8089:8089"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - mygrpcnetwork
    depends_on:
      - sm-db
      - social_media_redis
    restart: unless-stopped
    env_file:
      - base.env

  auth-service:
    image: kaium123/token-auth:2
    container_name: auth-service
    ports:
      - "50053:50053"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - mygrpcnetwork
    depends_on:
      - sm-db
    restart: unless-stopped
    environment:
      CONSUL_PATH: auth
      CONSUL_URL: consul:8500

  

  social_media_redis:
    container_name: social_media_redis
    image: 'redis:7-alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    networks:
      - mygrpcnetwork
    ports:
      - '63792:6379'

networks:
  mygrpcnetwork:
    driver: bridge


volumes:
  sm-db: {}
